version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server-manager
    restart: always
    # ports:
    #   - '3000:3000'

  server:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./server-manager/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - config/svm.env

    # TODO: pass env var for password

volumes:
  caddy_data:
    external: true
  caddy_config:
